### ISSUE TITLE
libmodulemd 1.7 segfaults if given a module without a name

### ISSUE THREAD

**Issue by r4f4** [fedora-modularity/libmodulemd#125]
Trying to run `modulemd_index_from_file` with a module without a name will cause libmodulemd to segfault.

To reproduce the issue, use the following module description:
```
document: modulemd
version: 2
data:
  summary: test
```
and the following executable:
```c
#include <stdio.h>
#include <glib.h>
#include <modulemd.h>

const char *file = "test.yaml";

int
main(int argc, char *argv[])
{
    g_autoptr(GError) error = NULL;
    g_autoptr(GHashTable) index = NULL;
    g_autoptr(GPtrArray) failures = NULL;

    index = modulemd_index_from_file(file, &failures, &error);
    for (int i = 0; i < failures->len; i++) {
        const GError *e = modulemd_subdocument_get_gerror(g_ptr_array_index(failures, i));
        g_debug(e->message);
    }

    if (error != NULL)
        g_warning(error->message);

    return 0;
}
```

**Comment by r4f4** [comment]
gcc output of the above program:
```
Program received signal SIGSEGV, Segmentation fault.
g_str_hash (v=0x0) at ghash.c:1955
1955	  for (p = v; *p != '\0'; p++)
(gdb) up
#1  0x00007ffff7eca5a0 in g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0x0, 
    hash_table=0x430120) at ghash.c:379
379	  hash_value = hash_table->hash_func (key);
(gdb) up
#2  g_hash_table_lookup (hash_table=hash_table@entry=0x430120, key=key@entry=0x0) at ghash.c:1153
1153	  node_index = g_hash_table_lookup_node (hash_table, key, &node_hash);
(gdb) up
#3  0x00007ffff7e45c29 in get_or_create_module_from_index (htable=htable@entry=0x430120, 
    module_name=module_name@entry=0x0) at ../modulemd/v1/modulemd-util.c:352
352	  stored_module = g_hash_table_lookup (htable, module_name);
```
