### ISSUE TITLE
modulemd_objects_from_file fails with `error` set to NULL

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-modularity/libmodulemd#53]
```c
  g_autoptr(GPtrArray) objects = modulemd_objects_from_file (pool_tmpjoin (pool, TEST_DIR, fname, NULL), NULL);

  for (guint i = 0; i < objects->len; i++)
    {
      if (MODULEMD_IS_MODULE (g_ptr_array_index (objects, i)))
        {
          ModulemdModule *module = g_ptr_array_index (objects, i);
          add_module_solvables (repo, module);
        }
    }
```

code like this fails with
```
** Message: 11:54:53.974: GError is initialized.
fish: “and ./build/main” terminated by signal SIGSEGV (Address boundary error)
```

Moreover, it segfaults:
```
#0  0x00007ffff6e33cdf in free () at /lib64/libc.so.6
#1  0x00007ffff58a2c12 in yaml_parser_delete (parser=parser@entry=0x7fffffffdea0) at api.c:218
        __PRETTY_FUNCTION__ = "yaml_parser_delete"
#2  0x00007ffff73e2495 in parse_yaml_file (path=0x62e670 "/home/brain/tmp/m/data/repodata/8e7a1438e8668c6a8a74eb6d9ff3362f8039dd5f4ab25a4bb2db30e685e639d8-modules.yaml.gz", data=data@entry=0x7fffffffe0c0, error=<optimized out>) at ../modulemd/modulemd-yaml-parser.c:113
        result = 0
        yaml_file = 0x0
        parser = 
          {error = 544497952, problem = 0x74737961682f2f3a <error: Cannot access memory at address 0x74737961682f2f3a>, problem_offset = 0, problem_value = 0, problem_mark = {index = 0, line = 0, column = 0}, context = 0x0, context_mark = {index = 0, line = 0, column = 0}, read_handler = 0x0, read_handler_data = 0x0, input = {string = {start = 0x0, end = 0x0, current = 0x0}, file = 0x0}, eof = 4202117, buffer = {start = 0x629250 "\360\222b", end = 0x8000000100000007 <error: Cannot access memory at address 0x8000000100000007>, pointer = 0x610730 "", last = 0x629250 "\360\222b"}, unread = 6478576, raw_buffer = {start = 0x62af0d "\201C\216z\024\070\350f\214j\212t\353m\237\363\066/\200\071\335_J\262ZK\262\333\060\346\205\346\071\330]\r=\263\006\\3\203mvi<\373('\214\036\032\235P\030W\347\b\a\244\177\222\341\260U\252repodata/8e7a1438e8668c6a8a74eb6d9ff3362f8039dd5f4ab25a4bb2db30e685e639d8-modules.yaml.gz", end = 0x62af0f "\216z\024\070\350f\214j\212t\353m\237\363\066/\200\071\335_J\262ZK\262\333\060\346\205\346\071\330]\r=\263\006\\3\203mvi<\373('\214\036\032\235P\030W\347\b\a\244\177\222\341\260U\252repodata/8e7a1438e8668c6a8a74eb6d9ff3362f8039dd5f4ab25a4bb2db30e685e639d8-modules.yaml.gz", pointer = 0x0, last = 0x62d534 "\002"}, encoding = 6521616, offset = 195, mark = {index = 2, line = 0, column = 0}, stream_start_produced = 0, stream_end_produced = 0, flow_level = 0, tokens = {start = 0x0, end = 0x0, head = 0x0, tail = 0x0}, tokens_parsed = 0, token_available = 0, indents = {start = 0x0, end = 0x0, top = 0x0}, indent = 0, simple_key_allowed = 0, simple_keys = {start = 0x0, end = 0x0, top = 0x0}, states = {start = 0x0, end = 0x0, top = 0x0}, state = YAML_PARSE_STREAM_START_STATE, marks = {start = 0x0, end = 0x0, top = 0x0}, tag_directives = {start = 0x0, end = 0x0, top = 0x0}, aliases = {start = 0x0, end = 0x0, top = 0x0}, document = 0x0}
        __func__ = "parse_yaml_file"
#3  0x00007ffff73ca168 in modulemd_objects_from_file (yaml_file=<optimized out>, error=<optimized out>) at ../modulemd/modulemd-common.c:53
        data = 0x0
        __func__ = "modulemd_objects_from_file"
#4  0x0000000000401cd6 in main () at ../main.c:205
        fp = 0x62e510
        pool = 0x610730
        repo = 0x629250
        chksumtype = 52
        chksum = 0x62af0f "\216z\024\070\350f\214j\212t\353m\237\363\066/\200\071\335_J\262ZK\262\333\060\346\205\346\071\330]\r=\263\006\\3\203mvi<\373('\214\036\032\235P\030W\347\b\a\244\177\222\341\260U\252repodata/8e7a1438e8668c6a8a74eb6d9ff3362f8039dd5f4ab25a4bb2db30e685e639d8-modules.yaml.gz"
        fname = 0x62af4f "repodata/8e7a1438e8668c6a8a74eb6d9ff3362f8039dd5f4ab25a4bb2db30e685e639d8-modules.yaml.gz"
        objects = 0x7ffff7192369 <_g_signal_init+153>
```

**Comment by sgallagher** [comment]
@ignatenkobrain Can you include the YAML file that is failing to parse? I have no idea how to reproduce this situation.

**Comment by ignatenkobrain** [comment]
[8e7a1438e8668c6a8a74eb6d9ff3362f8039dd5f4ab25a4bb2db30e685e639d8-modules.yaml.gz](https://github.com/fedora-modularity/libmodulemd/files/1928052/8e7a1438e8668c6a8a74eb6d9ff3362f8039dd5f4ab25a4bb2db30e685e639d8-modules.yaml.gz)
