### ISSUE TITLE
TypeError: unbound method strip_gtype() must be called with ModulemdUtil instance as first argument

### ISSUE THREAD

**Issue by mikem23** [fedora-modularity/libmodulemd#537]
There appears to be an issue with some of the recent changes. The module fails to load in python, at least on el7

```
[root@cf4b71b1d045 /]# python
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version("Modulemd", "2.0")
>>> from gi.repository import Modulemd  # noqa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Modulemd.py", line 116, in <module>
    Modulemd.read_packager_file
TypeError: unbound method strip_gtype() must be called with ModulemdUtil instance as first argument (got FunctionInfo instance instead)
```

**Comment by mikem23** [comment]
This was in a fresh centos7 container with python2-libmodulemd2 installed from epel

**Comment by mikem23** [comment]
attn: @sgallagher

**Comment by sgallagher** [comment]
Merlin and I will look into this immediately.

**Comment by sgallagher** [comment]
@mikem23  https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-07fff01e4a should fix this for you. Thanks for reporting the issue!
