### ISSUE TITLE
No such file or directory: '/builddir/build/BUILD/modulemd-1.7.0/spec_tmpl.sh

### ISSUE THREAD

**Issue by tpgxyz** [fedora-modularity/libmodulemd#99]
latest version 1.7.0 does not build
More logs can be found here https://abf.openmandriva.org/build_lists/264186

```
ninja: Entering directory `build'
[1/64] Generating rpmsetup with a custom command.
[2/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-component-module.c.o'.
[3/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-buildopts.c.o'.
[4/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-common.c.o'.
[5/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-dependencies.c.o'.
../modulemd/v1/modulemd-dependencies.c:77:3: warning: passing 'typeof (*(&streams[0]))' (aka 'const char *') to parameter of type 'gpointer' (aka 'void *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  g_clear_pointer (&streams[0], g_free);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmem.h:121:18: note: expanded from macro 'g_clear_pointer'
      (destroy) (_ptr);                                                        \
                 ^~~~
/usr/include/glib-2.0/glib/gmem.h:71:35: note: passing argument to parameter 'mem' here
void     g_free           (gpointer      mem);
                                         ^
1 warning generated.
[6/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-component.c.o'.
[7/64] Generating specfile with a meson_exe.py custom command.
FAILED: libmodulemd.spec 
/usr/bin/meson --internal exe /builddir/build/BUILD/modulemd-1.7.0/build/meson-private/meson_exe_spec_tmpl.sh_bb026530aab33876f2f2aa904ab53932e74bbde4.dat
Traceback (most recent call last):
  File "/usr/bin/meson", line 11, in <module>
    load_entry_point('meson==0.48.1', 'console_scripts', 'meson')()
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 392, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 344, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 254, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/meson_exe.py", line 97, in run
    return run_exe(exe)
  File "/usr/lib/python3.7/site-packages/mesonbuild/scripts/meson_exe.py", line 79, in run_exe
    stderr=subprocess.PIPE)
  File "/usr/lib64/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/builddir/build/BUILD/modulemd-1.7.0/spec_tmpl.sh': '/builddir/build/BUILD/modulemd-1.7.0/spec_tmpl.sh'
[8/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-component-rpm.c.o'.
[9/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-defaults.c.o'.
[10/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-intent.c.o'.
[11/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-improvedmodule.c.o'.
[12/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-prioritizer.c.o'.
[13/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-modulestream.c.o'.
[14/64] Compiling C object 'modulemd/v1/modulemd@v1@@modulemd@sha/modulemd-module.c.o'.
ninja: build stopped: subcommand failed.
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.AbJ6pS (%build)
```

**Comment by sgallagher** [comment]
During the run of `/usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . build -Ddeveloper_build=false` we see the message:
```
Program spec_tmpl.sh found: YES (/builddir/build/BUILD/modulemd-1.7.0/spec_tmpl.sh)
```
So this file is *definitely* present. Could something be causing it to be deleted after that? It's building just fine in [my Travis CI environment](https://travis-ci.org/fedora-modularity/libmodulemd) for Fedora Rawhide.

I can write a patch to skip generating the specfile for packager builds (it's not necessary), but I'd prefer to figure out why this is working on Fedora and not on Mandriva.

**Comment by sgallagher** [comment]
Oh, interesting. It looks like if /usr/bin/sh isn't present on the system, it displays that message. I didn't realize that could happen on Mandriva. I'll add a proper find_programs() call for that.

**Comment by Conan-Kudo** [comment]
@sgallagher For further explanation, OpenMandriva has not undergone [UsrMerge](https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/), so `/bin` is not a symlink to `/usr/bin`.
